import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import IconCal from '@/assets/IconCal.png';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Calculadora NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Calculadora NEXT</title>
        <link rel="icon" href={IconCal.src} type="image/png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
